import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "node:path";

export default defineConfig({
  base: "/_devtools/",

  plugins: [
    react(),
    tailwindcss(),
  ],

  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
    },
  },

  build: {
    // Package the dashboard with the ServerDevTools SDK.
    outDir: "../dist/dashboard",
    // Do not delete dist/src generated by the TypeScript build.
    emptyOutDir: false,
  },

  server: {
    // Development only: proxy the Vite dashboard to the local example backend.
    proxy: {
      "/_devtools/api": {
        target: "http://localhost:3000",
        changeOrigin: true,
      },
    },
  },
});
